server:
  port: 8090

spring:
  application:
    name: api-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

zuul:
  routes:
    books:
      path: /book-service/**
      serviceId: book-service
      stripPrefix: true
    users:
      path: /user-service/**
      serviceId: user-service
      stripPrefix: true
    analytics:
      path: http://analytic-service/**
      serviceId: analytics-service
      stripPrefix: true
    reservations:
      path: http://reservation-service/**
      serviceId: reservation-service
      stripPrefix: true